//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanTraSua.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        public MonAn()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTPNs = new HashSet<CTPN>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string MaLoai { get; set; }
    
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual ICollection<CTPN> CTPNs { get; set; }
        public virtual LoaiMon LoaiMon { get; set; }
    }
}
