//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public string MaPN { get; set; }
        public string MaMon { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
